# Generated by Django 5.1.6 on 2025-03-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('shopify', 'Shopify'), ('uniconta', 'Uniconta')], max_length=20)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('api_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval', models.PositiveIntegerField(default=1440)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(choices=[('ftp', 'FTP'), ('url', 'URL'), ('local', 'LOCAL')], max_length=10)),
                ('feed_product_tag', models.CharField(default='item', max_length=30)),
                ('ftp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('ftp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('ftp_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_pattern', models.CharField(default='products.xml', max_length=255)),
                ('format_type', models.CharField(choices=[('xml', 'XML')], max_length=10)),
                ('mapping', models.JSONField(blank=True, default=dict, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('shops', models.ManyToManyField(related_name='feeds', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.feed')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
