# Generated by Django 5.1.6 on 2025-03-03 19:41

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shop_type', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('other', 'Other')], default='other', max_length=20)),
                ('api_endpoint', models.URLField()),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('api_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval', models.CharField(default='daily', help_text='e.g., hourly, daily', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ftp', 'FTP'), ('url', 'URL')], default='ftp', max_length=10)),
                ('ftp_host', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_user', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('ftp_pass', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_pattern', models.CharField(default='products.xml', help_text='e.g., products*.xml', max_length=100)),
                ('format_type', models.CharField(choices=[('xml', 'XML'), ('csv', 'CSV')], default='xml', max_length=10)),
                ('mapping', models.JSONField(default=dict, help_text="e.g., {'name': 'product_title', 'price': 'product_price'}")),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='shops.shop')),
            ],
        ),
    ]
